controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      critics: ["RotateToGoal", "Oscillation", "ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      RotateToGoal:
        scale: 1.0
      Oscillation:
        scale: 1.0
      ObstacleFootprint:
        scale: 1.0
      GoalAlign:
        scale: 1.0
      PathAlign:
        scale: 1.0
      PathDist:
        scale: 1.0
      GoalDist:
        scale: 1.0

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"

